version: '3'

services: 
   
  app:
    container_name: phonecatalogue_app
    #image: phone_catalogue
    restart: always
    ports: 
      - "3002:3002" #host_port:container_port
    #build: .
    image: irenegl3/phonecatalogue:latest
    depends_on:
      - db
    env_file:
      - phone-catalogue.env

  db:
    container_name: phonecatalogue_db
    image: postgres:latest
    restart: always
    volumes:
      - ./init.sql:/init.sql
    env_file:
      - phone-catalogue-db.env
